### ISSUE TITLE
chart.time is incorrect

### ISSUE THREAD

**Issue by acc4012** [sebastianGehrmann/phenotyping#1]
Hello, 
I cannot generate the data because chart.time is either 999999 or identical to admission id. 
Could you please check? 

- Usually there is no chart.time for discharge summary. For example, the first record in the csv, there is not chart.time in mimic3 for all discharge summaries. Then, it is difficult to match with the data provided in the csv. 
- I think it is better to provide ROW_ID too, so that the notes are identified correctly. 

- Other comment: Also, Many HADM_ID and SUBJECT_ID are duplicated. This could be a problem for data quality because they may be somehow similar.

**Comment by sebastianGehrmann** [comment]
This problem stems from porting annotations from MIMIC II to MIMIC III, and are not all fixable. The 999 values are for notes in which chart time was not available. We have a tutorial for matching at https://ektar.github.io/2016/mimic-iii-note-matching.html
Additionally, if you request our full data on Physionet, you will be able to match on entire notes (which we found to be the most reliable matching).

**Comment by acc4012** [comment]
Many thanks! I will check them out.
